name = "d1-cfpages-basic"
main = "src/index.js"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "MY_DATABASE"    # i.e. available in the Worker on env.MY_DATABASE
database_name = "d1-cfpages-basic"
database_id = "3c6be680-26c4-4635-91ed-71a5c42cac5b"
