name: check-for-update
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  check-for-latest-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: check latest update
        run: sh .github/scripts/check-for-update.sh latest latest
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-dev-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: check dev update
        run: sh .github/scripts/check-for-update.sh dev master
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  report-to-slack-failure:
    runs-on: ubuntu-latest
    needs: [check-for-latest-update, check-for-dev-update]
    if: failure()
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: report failure to slack
        run: bash .github/scripts/slack-workflow-status.sh "check-for-update :x:"
        env:
          SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_WORKFLOWS }}
