name: check-for-update
on:
  # Manual UI in GitHub https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
  schedule:
    # Run every five minutes
    - cron: '*/5 * * * *'

concurrency: check-for-update

env:
  PRISMA_TELEMETRY_INFORMATION: 'ecosystem-tests check-for-update.yaml'

jobs:
  check-for-latest-update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: check latest update
        run: pnpm run update-ci latest
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-dev-update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: check dev update
        run: pnpm run update-ci dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-patch-dev-update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: check patch-dev update
        run: pnpm run update-ci patch-dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-integration-update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: check integration update
        run: pnpm run update-ci integration
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  report-to-slack-failure:
    runs-on: ubuntu-20.04
    needs:
      - check-for-latest-update
      - check-for-dev-update
      - check-for-patch-dev-update
      - check-for-integration-update
    if: failure()
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: report failure to slack
        run: bash .github/scripts/slack-workflow-status.sh "check-for-update :x:"
        env:
          SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_WORKFLOWS }}
