name: test and lint test suite

on:
  push:
    paths-ignore:
      - '*.md'
      - 'renovate.json'

jobs:
  check-test-suite-coverage:
    runs-on: ubuntu-20.04

    # Ignore if renovate (dependency update) or if triggerred by auto update
    # Needs to be in a string because the colon after chore breaks yaml
    if: "${{ !contains(github.actor, 'renovate') && !contains(github.event.head_commit.message, 'chore: sync, use') }}"

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.3.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: lint test suite coverage
        run: node .github/scripts/check-folders.js

      - name: run detect-jobs-to-run tests
        run: pnpm exec jest detect-jobs-to-run
