name: optional-test
on: push
env:
  PRISMA_TELEMETRY_INFORMATION: 'e2e-tests optional-test.yaml'
  SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_OPTIONAL_WORKFLOWS }}

jobs:
  start-time:
    runs-on: ubuntu-latest
    outputs:
      start-time: ${{ steps.start-time-output.outputs.start-time }}
    steps:
      - id: start-time-output
        run: echo "::set-output name=start-time::$(date)"

  report-to-slack-success:
    runs-on: ubuntu-latest
    needs:
      - community-generators

    if: success() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration' || github.ref == 'refs/heads/patch-dev' || github.ref == 'refs/heads/latest')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: report success to slack
        run: bash .github/slack/notify-workflow-result.sh "(Optional tests) :white_check_mark:"

  report-to-slack-failure:
    runs-on: ubuntu-latest
    needs:
      - community-generators
    if: failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration' || github.ref == 'refs/heads/patch-dev' || github.ref == 'refs/heads/latest')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: report failure to slack
        run: bash .github/slack/notify-workflow-result.sh "(Optional tests) :x:"

  community-generators:
    needs: start-time
    strategy:
      fail-fast: false
      matrix:
        feature:
          [
            prisma-dbml-generator,
            typegraphql-prisma,
            prisma-json-schema-generator,
          ]
    runs-on: ubuntu-latest
    env:
      START_TIME: ${{ needs.start-time.outputs.start-time }}
      CI: 1
      # TODO: Consolidate these env vars. They shouldn't be required for slack notification
      # They are only required because `test-project.sh` hardcodes the names
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_OPTIONAL_TESTS_SUCCESS }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_OPTIONAL_TESTS_FAILING }}
      ##
      SLACK_WEBHOOK_URL_OPTIONAL_TESTS_SUCCESS: ${{ secrets.SLACK_WEBHOOK_URL_OPTIONAL_TESTS_SUCCESS }}
      SLACK_WEBHOOK_URL_OPTIONAL_TESTS_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_OPTIONAL_TESTS_FAILING }}
      SKIP_PRISMA_VERSION_CHECK: true # see https://github.com/MichalLytek/typegraphql-prisma/issues/31
      DB_URL_COMMUNITY_GENERATOR_TYPEGRAPHQL_PRISMA: ${{ secrets.DB_URL_COMMUNITY_GENERATOR_TYPEGRAPHQL_PRISMA }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: test feature - ${{ matrix.feature }}
        id: run-test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh community-generators ${{ matrix.feature }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-job-failure.sh community-generators ${{ matrix.feature }}
