name: upgrade
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

#      - name: upgrade
#        run: sh upgrade.sh
#        env:
#          SSH_KEY: ${{ secrets.SSH_KEY }}
